
version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"
dependency_file_paths = ["requirements/development.txt"]

  [analyzers.meta]
  max_line_length = 88
  skip_doc_coverage = ["module", "magic", "init"]
